---
sudo: false
language: ruby
cache: bundler
# available rubies are located at http://rubies.travis-ci.org/
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
# no binary available
#   - 2.6.4
before_install: gem install bundler -v 1.17.3
script:
  - bundle exec rake 
